const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  EXTERNAL_ANIME_API_ERROR: 'EXTERNAL_ANIME_API_ERROR',
  EXTERNAL_ANIME_API_RATE_LIMITED: 'EXTERNAL_ANIME_API_RATE_LIMITED',
  EXTERNAL_ANIME_API_BAD_REQUEST: 'EXTERNAL_ANIME_API_BAD_REQUEST',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_REQUIRED: 'AUTH_TOKEN_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',
  ANIME_ALREADY_IN_LIBRARY: 'ANIME_ALREADY_IN_LIBRARY',
  FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
};

module.exports = { ERROR_CODES };
